package kdms.ddl;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

import kdms.catalog.SourceCatalog;
import kdms.catalog.SourceDataScanner;
import kdms.config.KdmsConfig;
import kdms.ddl.SchemaPlan.Issue;
import kdms.ddl.SchemaPlan.TablePlan;
import kdms.rules.RulesLoader;

class SchemaPlannerTest {

    static final KdmsConfig.TableSelection ALL = new KdmsConfig.TableSelection(List.of("dbo.*"), List.of());

    /** 저장소의 KDMS_MOCK 용 규칙(config/kdms-rules.yml)으로 만든 계획 */
    static SchemaPlan mockPlan() {
        return SchemaPlanner.plan(KdmsMockCatalog.catalog(), ALL, RulesLoader.load(Path.of("config/kdms-rules.yml")), null);
    }

    /**
     * 2단계 완료 기준(plan.md §6): KIS sql/20_pg/gen/mock.sql(2026-09-30 생성)의 테이블 정의와 같은 타입.
     * 아래 값은 그 파일에서 그대로 옮겼다. file_attach 는 mock.sql 생성 뒤 KIS #23 이 더한 테이블이라
     * KIS sql/10_mssql/20_gen_pg_ddl.sql 의 같은 타입 규칙으로 손으로 계산했다.
     */
    @Test
    void KDMS_MOCK_대상_타입은_KIS_mock_sql_과_같다() {
        Map<String, String> kis = new LinkedHashMap<>();
        kis.put("app_user", "user_id integer, login_id varchar(30), user_nm varchar(50), email varchar(100), member_level smallint, joined_dtm timestamp(3)");
        kis.put("code_master", "code_grp varchar(20), code varchar(10), code_nm varchar(100), code_nm_short varchar(20), sort_no smallint, use_yn char(1)");
        kis.put("daily_count", "snap_dt date, table_nm varchar(128), row_cnt bigint");
        kis.put("file_attach", "file_id integer, case_cd varchar(10), case_desc varchar(200), file_nm varchar(260), file_nm_a varchar(260), "
                + "file_path varchar(400), file_url varchar(2000)");
        kis.put("issuer", "issuer_id integer, issuer_cd char(6), issuer_nm varchar(100), issuer_nm_cp949 varchar(40), issuer_nm_en varchar(200), "
                + "region_cd char(2), industry_cd varchar(2), is_listed boolean, issuer_guid uuid, row_ver bytea, reg_dtm timestamp(3), upd_dtm timestamp(6)");
        kis.put("rating", "rating_id bigint, issuer_id integer, rating_cd varchar(10), outlook_cd char(1), rating_dt date, eff_dtm timestamp(3), "
                + "issue_amt numeric(19,4), coupon_rate numeric(9,4), is_watch boolean, rating_rank integer");
        kis.put("rating_hist", "hist_id bigint, rating_id bigint, action_cd char(1), old_rating_cd varchar(10), new_rating_cd varchar(10), "
                + "changed_by varchar(128), changed_dtm timestamp(3)");
        kis.put("research_doc", "doc_id integer, doc_no bigint, doc_type_cd varchar(2), issuer_id integer, title varchar(400), file_nm varchar(100), "
                + "file_path varchar(400), file_ext varchar(200), pub_dtm timestamp(3), body text, view_cnt integer");

        SchemaPlan p = mockPlan();
        Map<String, String> ours = new LinkedHashMap<>();
        for (TablePlan t : p.tables()) {
            ours.put(t.tgtName(), String.join(", ", t.columns().stream().map(c -> c.tgtName() + " " + c.tgtType()).toList()));
        }
        assertThat(ours).isEqualTo(kis);
    }

    @Test
    void KDMS_MOCK_은_오류없이_통과하고_규칙_결정이_DDL_에_보인다() {
        SchemaPlan p = mockPlan();
        assertThat(p.allIssues().stream().filter(i -> i.level() == Issue.Level.ERROR)).isEmpty();
        assertThat(p.blocked()).isFalse();

        String pre = DdlWriter.write(p, DdlWriter.Phase.PRE_LOAD);
        assertThat(pre)
                .contains("CREATE SCHEMA IF NOT EXISTS \"dbo\"")
                .contains("CREATE SEQUENCE \"dbo\".\"seq_doc_no\" AS bigint START WITH 202600001 INCREMENT BY 1 "
                        + "MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE")
                .contains("\"user_id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL")
                .contains("\"login_id\" varchar(30) COLLATE \"C\" NOT NULL")
                .contains("\"member_level\" smallint DEFAULT 0 NOT NULL CHECK (\"member_level\" BETWEEN 0 AND 255)")  // tinyint
                .contains("\"joined_dtm\" timestamp(3) DEFAULT LOCALTIMESTAMP NOT NULL")                              // getdate()
                .contains("\"use_yn\" char(1) COLLATE \"C\" DEFAULT 'Y' NOT NULL")
                .contains("\"is_listed\" boolean DEFAULT false NOT NULL")                                             // ((0)) → false
                .contains("\"issuer_guid\" uuid DEFAULT gen_random_uuid() NOT NULL")                                  // newsequentialid()
                .contains("\"changed_by\" varchar(128) COLLATE \"C\" DEFAULT session_user NOT NULL")                  // suser_sname()
                .contains("\"doc_no\" bigint DEFAULT nextval('\"dbo\".\"seq_doc_no\"'::regclass) NOT NULL")           // B13
                .contains("\"rating_rank\" integer GENERATED ALWAYS AS (CASE upper(rtrim(rating_cd)) WHEN 'AAA' THEN 1")  // B12
                .contains("\"file_ext\" varchar(200) COLLATE \"C\" GENERATED ALWAYS AS (CASE WHEN strpos(file_nm, '.') > 0")
                .contains("CONSTRAINT \"pk_code_master\" PRIMARY KEY (\"code_grp\", \"code\")")
                .contains("COMMENT ON COLUMN \"dbo\".\"rating\".\"rating_rank\" IS 'MS-SQL 계산 컬럼 원문: (case rtrim([rating_cd]) when ''AAA''")
                .doesNotContain("FOREIGN KEY")
                .doesNotContain("INDEX");

        String post = DdlWriter.write(p, DdlWriter.Phase.POST_LOAD);
        assertThat(post)
                .contains("CREATE UNIQUE INDEX \"uq_app_user_login\" ON \"dbo\".\"app_user\" (lower(\"login_id\"))")  // B14
                .contains("CREATE UNIQUE INDEX \"uq_issuer_cd\" ON \"dbo\".\"issuer\" (lower(\"issuer_cd\"))")
                .contains("CREATE UNIQUE INDEX \"pk_code_master_ci\" ON \"dbo\".\"code_master\" (lower(\"code_grp\"), lower(\"code\"))")
                .contains("CREATE UNIQUE INDEX \"pk_daily_count_ci\" ON \"dbo\".\"daily_count\" (\"snap_dt\", lower(\"table_nm\"))")
                .contains("CREATE INDEX \"ix_rating_issuer_dt\" ON \"dbo\".\"rating\" (\"issuer_id\", \"rating_dt\")")
                .contains("CREATE INDEX \"ix_issuer_nm\" ON \"dbo\".\"issuer\" (\"issuer_nm\")");

        String cut = DdlWriter.write(p, DdlWriter.Phase.CUTOVER);
        assertThat(cut)
                .contains("ALTER TABLE \"dbo\".\"rating\" ADD CONSTRAINT \"fk_rating_issuer\" FOREIGN KEY (\"issuer_id\") "
                        + "REFERENCES \"dbo\".\"issuer\" (\"issuer_id\")")
                .contains("\"fk_doc_issuer\"");

        TablePlan rating = p.tables().stream().filter(t -> t.tgtName().equals("rating")).findFirst().orElseThrow();
        assertThat(rating.loadColumns()).extracting(SchemaPlan.ColumnPlan::tgtName).doesNotContain("rating_rank").hasSize(9);
    }

    @Test
    void 경고와_주의가_KIS_함정을_짚는다() {
        SchemaPlan p = mockPlan();
        String warns = String.join("\n", p.allIssues().stream().filter(i -> i.level() == Issue.Level.WARN).map(Issue::toString).toList());
        assertThat(warns)
                .contains("트리거 trg_rating_audit")                 // B11
                .contains("uniqueidentifier → uuid")
                .contains("rowversion → bytea")
                .contains("newsequentialid")
                .contains("getdate")
                .contains("자동 변환하지 않는 객체 6개");
        String notes = String.join("\n", p.allIssues().stream().filter(i -> i.level() == Issue.Level.NOTE).map(Issue::message).toList());
        assertThat(notes).contains("B01").contains("B02").contains("A03");

        SchemaPlan.ColumnPlan upd = p.tables().stream().filter(t -> t.tgtName().equals("issuer")).findFirst().orElseThrow()
                .columns().stream().filter(c -> c.srcName().equals("upd_dtm")).findFirst().orElseThrow();
        assertThat(upd.value().round()).isEqualTo("half_up");                // A06
        assertThat(upd.value().sentinel()).isEqualTo("keep");                // A08
    }

    @Test
    void 기본_규칙만_쓰면_계산_컬럼_식이_없어_막힌다() {
        SchemaPlan p = SchemaPlanner.plan(KdmsMockCatalog.catalog(), ALL, RulesLoader.load(null), null);
        assertThat(p.blocked()).isTrue();
        assertThat(p.allIssues()).filteredOn(i -> i.level() == Issue.Level.ERROR).extracting(Issue::where)
                .containsExactlyInAnyOrder("dbo.rating.rating_rank", "dbo.research_doc.file_ext");
    }

    @Test
    void 값만_옮기기를_고르면_KIS_처럼_일반_컬럼과_COMMENT() throws Exception {
        Path f = java.nio.file.Files.createTempFile("rules", ".yml");
        java.nio.file.Files.writeString(f, "computed_columns: { action: value_with_warning }\n");
        SchemaPlan p = SchemaPlanner.plan(KdmsMockCatalog.catalog(), ALL, RulesLoader.load(f), null);
        assertThat(p.blocked()).isFalse();
        String pre = DdlWriter.write(p, DdlWriter.Phase.PRE_LOAD);
        assertThat(pre).contains("\"rating_rank\" integer,").contains("MS-SQL 계산 컬럼(값만 이관) 원문");
        java.nio.file.Files.delete(f);
    }

    @Test
    void 테이블_선택과_제외() {
        SchemaPlan p = SchemaPlanner.plan(KdmsMockCatalog.catalog(),
                new KdmsConfig.TableSelection(List.of("dbo.rating*", "dbo.issuer"), List.of("dbo.rating_hist")),
                RulesLoader.load(Path.of("config/kdms-rules.yml")), null);
        assertThat(p.tables()).extracting(TablePlan::tgtName).containsExactly("issuer", "rating");
        assertThat(p.excluded()).extracting(SchemaPlan.Excluded::table).containsExactly("dbo.rating_hist");
        // research_doc 이 빠졌으므로 시퀀스는 dbo 스키마라 남지만 FK fk_doc_issuer 는 없다
        assertThat(DdlWriter.write(p, DdlWriter.Phase.CUTOVER)).contains("fk_rating_issuer").doesNotContain("fk_doc_issuer");
    }

    @Test
    void FK_가_빠진_테이블을_가리키면_경고하고_만들지_않는다() {
        SchemaPlan p = SchemaPlanner.plan(KdmsMockCatalog.catalog(), new KdmsConfig.TableSelection(List.of("dbo.rating"), List.of()),
                RulesLoader.load(Path.of("config/kdms-rules.yml")), null);
        assertThat(DdlWriter.write(p, DdlWriter.Phase.CUTOVER)).doesNotContain("FOREIGN KEY");
        assertThat(p.allIssues()).anyMatch(i -> i.message().contains("dbo.issuer 이 이관 대상이 아니라"));
    }

    @Test
    void 스키마_이름_바꾸기와_규칙_오타_경고() throws Exception {
        Path f = java.nio.file.Files.createTempFile("rules", ".yml");
        java.nio.file.Files.writeString(f, """
                identifiers:
                  schemas: { dbo: mock }
                  map: { dbo.app_user: users }
                computed_columns: { action: value_with_warning }
                tables:
                  dbo.no_such: { exclude: true }
                  dbo.issuer:
                    columns:
                      no_such_col: { trailing_space: rtrim }
                      issuer_nm: { name: issuer_name }
                """);
        SchemaPlan p = SchemaPlanner.plan(KdmsMockCatalog.catalog(), ALL, RulesLoader.load(f), null);
        String pre = DdlWriter.write(p, DdlWriter.Phase.PRE_LOAD);
        assertThat(pre).contains("CREATE TABLE \"mock\".\"users\"").contains("\"issuer_name\" varchar(100)")
                .contains("nextval('\"mock\".\"seq_doc_no\"'::regclass)");
        assertThat(DdlWriter.write(p, DdlWriter.Phase.POST_LOAD)).contains("ON \"mock\".\"issuer\" (\"issuer_name\")");
        assertThat(p.allIssues()).extracting(Issue::where).contains("규칙 tables.dbo.no_such", "규칙 tables.dbo.issuer.columns.no_such_col");
        java.nio.file.Files.delete(f);
    }

    @Test
    void 규칙_없는_타입_긴_이름_모르는_기본값은_오류() {
        SourceCatalog.Column geo = KdmsMockCatalog.col(2, "loc", "geography", -1, 0, 0, true);
        SourceCatalog.Column longName = KdmsMockCatalog.col(3, "c".repeat(64), "int", 4, 10, 0, true);
        SourceCatalog.Column odd = KdmsMockCatalog.withDefault(KdmsMockCatalog.col(4, "d", "int", 4, 10, 0, true), "df_d", "(abs(-1))");
        SourceCatalog.Table t = KdmsMockCatalog.table("odd", 0,
                List.of(KdmsMockCatalog.col(1, "id", "int", 4, 10, 0, false), geo, longName, odd),
                List.of(KdmsMockCatalog.pk("pk_odd", "id")), List.of(), List.of());
        SourceCatalog cat = new SourceCatalog("X", KdmsMockCatalog.CI, List.of(t), List.of(), List.of());
        SchemaPlan p = SchemaPlanner.plan(cat, ALL, RulesLoader.load(null), null);
        assertThat(p.allIssues()).filteredOn(i -> i.level() == Issue.Level.ERROR).extracting(Issue::message)
                .anySatisfy(m -> assertThat(m).contains("타입 규칙 없음: geography"))
                .anySatisfy(m -> assertThat(m).contains("63바이트"))
                .anySatisfy(m -> assertThat(m).contains("자동으로 옮기지 않는 식: (abs(-1))"));
    }

    @Test
    void 인덱스_이름이_테이블마다_같으면_대상에선_바꾼다() {
        SourceCatalog.Table a = KdmsMockCatalog.table("a", 0, List.of(KdmsMockCatalog.col(1, "id", "int", 4, 10, 0, false)),
                List.of(KdmsMockCatalog.pk("pk_a", "id"), KdmsMockCatalog.index("ix_id", "id")), List.of(), List.of());
        SourceCatalog.Table b = KdmsMockCatalog.table("b", 0, List.of(KdmsMockCatalog.col(1, "id", "int", 4, 10, 0, false)),
                List.of(KdmsMockCatalog.pk("pk_b", "id"), KdmsMockCatalog.index("ix_id", "id")), List.of(), List.of());
        SchemaPlan p = SchemaPlanner.plan(new SourceCatalog("X", KdmsMockCatalog.CI, List.of(a, b), List.of(), List.of()), ALL,
                RulesLoader.load(null), null);
        assertThat(DdlWriter.write(p, DdlWriter.Phase.POST_LOAD))
                .contains("CREATE INDEX \"ix_id\" ON \"dbo\".\"a\"")
                .contains("CREATE INDEX \"ix_id_b\" ON \"dbo\".\"b\"");
    }

    @Test
    void NULL_허용_UNIQUE_는_NULLS_NOT_DISTINCT_필터_인덱스는_WHERE() {
        SourceCatalog.Column code = KdmsMockCatalog.col(2, "code", "int", 4, 10, 0, true);
        SourceCatalog.Column email = KdmsMockCatalog.text(3, "email", "varchar", 100, true);
        SourceCatalog.Table t = KdmsMockCatalog.table("u", 0,
                List.of(KdmsMockCatalog.col(1, "id", "int", 4, 10, 0, false), code, email),
                List.of(KdmsMockCatalog.pk("pk_u", "id"),
                        new SourceCatalog.Index("uq_code", SourceCatalog.IndexKind.UNIQUE_CONSTRAINT, 2, "NONCLUSTERED", false, null,
                                List.of(new SourceCatalog.IndexColumn("code", false)), List.of()),
                        new SourceCatalog.Index("ux_email", SourceCatalog.IndexKind.UNIQUE_INDEX, 2, "NONCLUSTERED", false,
                                "([email] IS NOT NULL)", List.of(new SourceCatalog.IndexColumn("email", false)), List.of())),
                List.of(), List.of());
        SchemaPlan p = SchemaPlanner.plan(new SourceCatalog("X", KdmsMockCatalog.CI, List.of(t), List.of(), List.of()), ALL,
                RulesLoader.load(null), null);
        assertThat(DdlWriter.write(p, DdlWriter.Phase.POST_LOAD))
                .contains("ALTER TABLE \"dbo\".\"u\" ADD CONSTRAINT \"uq_code\" UNIQUE NULLS NOT DISTINCT (\"code\")")
                .contains("CREATE UNIQUE INDEX \"ux_email\" ON \"dbo\".\"u\" (lower(\"email\")) WHERE (\"email\" IS NOT NULL)");
    }

    @Test
    void 필터_조건은_단순한_것만_옮긴다() {
        Map<String, String> cols = Map.of("a", "a", "b", "b_new");
        assertThat(SchemaPlanner.translateFilter("([a] IS NOT NULL AND [b]>(0))", cols)).isEqualTo("(\"a\" IS NOT NULL AND \"b_new\">(0))");
        assertThat(SchemaPlanner.translateFilter("([a]=N'Y')", cols)).isEqualTo("(\"a\"='Y')");
        assertThat(SchemaPlanner.translateFilter("([a]>getdate())", cols)).isNull();
        assertThat(SchemaPlanner.translateFilter("([zz] IS NULL)", cols)).isNull();
    }

    @Test
    void CI_콜레이션_규칙() throws Exception {
        Path f = java.nio.file.Files.createTempFile("rules", ".yml");
        java.nio.file.Files.writeString(f, "collation: { ci_unique: ci_collation }\ncomputed_columns: { action: value_with_warning }\n");
        SchemaPlan p = SchemaPlanner.plan(KdmsMockCatalog.catalog(), ALL, RulesLoader.load(f), null);
        String pre = DdlWriter.write(p, DdlWriter.Phase.PRE_LOAD);
        assertThat(pre).contains("CREATE COLLATION IF NOT EXISTS \"dbo\".\"kdms_ci\" (provider = icu, locale = 'und-u-ks-level2', deterministic = false)")
                .contains("\"login_id\" varchar(30) COLLATE \"dbo\".\"kdms_ci\" NOT NULL")
                .contains("\"email\" varchar(100) COLLATE \"C\"");
        assertThat(DdlWriter.write(p, DdlWriter.Phase.POST_LOAD)).contains("ADD CONSTRAINT \"uq_app_user_login\" UNIQUE (\"login_id\")")
                .doesNotContain("lower(");
        java.nio.file.Files.delete(f);
    }

    @Test
    void 데이터_검사_결과_NUL_은_fail_규칙이면_오류() {
        Map<String, SourceDataScanner.TableScan> scan = Map.of("dbo.research_doc", new SourceDataScanner.TableScan(10,
                Map.of("body", new SourceDataScanner.ColumnScan(2, 0), "pub_dtm", new SourceDataScanner.ColumnScan(0, 3))));
        SchemaPlan p = SchemaPlanner.plan(KdmsMockCatalog.catalog(), ALL, RulesLoader.load(Path.of("config/kdms-rules.yml")), scan);
        assertThat(p.blocked()).isTrue();
        assertThat(p.allIssues()).anyMatch(i -> i.level() == Issue.Level.ERROR && i.where().equals("dbo.research_doc.body")
                && i.message().contains("NUL 문자가 든 행 2건"));
        assertThat(p.allIssues()).anyMatch(i -> i.level() == Issue.Level.NOTE && i.message().contains("센티널 날짜 행 3건"));
    }

    @Test
    void 키_바이트_추정() {
        assertThat(SchemaPlanner.maxUtf8Bytes(KdmsMockCatalog.text(1, "a", "nvarchar", 900, false))).isEqualTo(1350);
        assertThat(SchemaPlanner.maxUtf8Bytes(KdmsMockCatalog.text(1, "a", "varchar", 40, false))).isEqualTo(60);
        assertThat(SchemaPlanner.maxUtf8Bytes(KdmsMockCatalog.text(1, "a", "nvarchar", -1, false))).isEqualTo(-1);
    }

    @Test
    void 보고서() {
        String r = PlanReport.render(mockPlan(), List.of("머리글"));
        assertThat(r).startsWith("머리글\n")
                .contains("요약: 테이블 8개 (PK 없음 0, 제외 0) · 컬럼 62개")
                .contains("결과: 통과")
                .contains("dbo.rating → dbo.rating")
                .contains("[적재 뒤] CREATE UNIQUE INDEX \"uq_app_user_login\"")
                .contains("[전환 때] ALTER TABLE \"dbo\".\"rating\" ADD CONSTRAINT \"fk_rating_issuer\"")
                .contains("== 자동 변환하지 않는 객체")
                .contains("SYNONYM 1: dbo.syn_region")
                .doesNotContain("== 오류");
    }
}
