package kdms.ddl;

import java.util.List;

import kdms.catalog.SourceCatalog;

/**
 * 원천 카탈로그 + 변환 규칙 → 대상 스키마 계획. {@link SchemaPlanner} 가 만들고
 * {@link DdlWriter}(DDL), {@link PlanReport}(보고서), 3단계 이후 적재기·반영기·검증이 쓴다.
 *
 * @param sourceDb        원천 DB 이름
 * @param sourceCollation 원천 DB 기본 콜레이션
 * @param tables          이관할 테이블
 * @param excluded        뺀 테이블("schema.table" 원천 이름)과 이유
 * @param sequences       만들 시퀀스
 * @param collations      비결정 ICU 콜레이션(kdms_ci)을 만들 대상 스키마
 * @param issues          테이블에 속하지 않는 오류·경고·주의
 * @param manualObjects   자동 변환하지 않는 객체(뷰·SP·함수·SYNONYM 등)
 */
public record SchemaPlan(
        String sourceDb,
        String sourceCollation,
        List<TablePlan> tables,
        List<Excluded> excluded,
        List<SequencePlan> sequences,
        List<String> collations,
        List<Issue> issues,
        List<SourceCatalog.DbObject> manualObjects) {

    /** 대상 스키마마다 만드는 비결정(대소문자 무시) ICU 콜레이션 이름 */
    public static final String CI_COLLATION = "kdms_ci";

    public record Excluded(String table, String reason) {
    }

    /** 오류가 하나라도 있으면 대상에 적용하지 않는다 */
    public boolean blocked() {
        return allIssues().stream().anyMatch(i -> i.level() == Issue.Level.ERROR);
    }

    /** 전체 + 테이블별 이슈 */
    public List<Issue> allIssues() {
        return java.util.stream.Stream.concat(issues.stream(), tables.stream().flatMap(t -> t.issues().stream())).toList();
    }

    public long count(Issue.Level level) {
        return allIssues().stream().filter(i -> i.level() == level).count();
    }

    /**
     * @param where 보고서에 보일 위치(예: dbo.rating.rating_rank)
     */
    public record Issue(Level level, String where, String message) {
        public enum Level {
            /** 고치기 전에는 대상에 적용하지 않는다 */
            ERROR,
            /** 적용은 하지만 사람이 확인할 것 */
            WARN,
            /** 이관 오류가 아니라 규칙 결정 때문에 조회 결과가 달라지는 곳(KIS B01~B14) */
            NOTE
        }
    }

    /**
     * @param srcSchema    원천 스키마
     * @param srcName      원천 테이블
     * @param tgtSchema    대상 스키마
     * @param tgtName      대상 테이블
     * @param rowsEstimate 원천 행 수(추정)
     * @param columns      컬럼(원천 순서)
     * @param primaryKey   PK, 없으면 null(전환 때 전체 재적재, plan.md §4.6)
     * @param postLoad     적재 뒤 만들 UNIQUE·인덱스
     * @param foreignKeys  전환 때 만들 FK
     * @param comments     COMMENT ON COLUMN (대상 컬럼 → 내용)
     * @param issues       이 테이블의 오류·경고·주의
     */
    public record TablePlan(
            String srcSchema,
            String srcName,
            String tgtSchema,
            String tgtName,
            long rowsEstimate,
            List<ColumnPlan> columns,
            KeyPlan primaryKey,
            List<IndexPlan> postLoad,
            List<ForeignKeyPlan> foreignKeys,
            List<Issue> issues) {

        public String srcQualified() {
            return srcSchema + "." + srcName;
        }

        public String tgtQualified() {
            return Names.quote(tgtSchema) + "." + Names.quote(tgtName);
        }

        /** 전체 적재·CDC 반영에서 값을 넣는 컬럼(GENERATED 컬럼 제외) */
        public List<ColumnPlan> loadColumns() {
            return columns.stream().filter(c -> c.generated() == null).toList();
        }
    }

    /**
     * @param srcName   원천 컬럼
     * @param srcType   원천 타입 표시(예: nvarchar(100), int IDENTITY(1,1))
     * @param tgtName   대상 컬럼
     * @param tgtType   대상 타입(예: varchar(100))
     * @param collate   COLLATE 절(예: "C"), 문자 컬럼이 아니면 null
     * @param nullable  NULL 허용
     * @param identity  IDENTITY 절(예: GENERATED BY DEFAULT AS IDENTITY), 없으면 null
     * @param defaultExpr 기본값 식, 없으면 null
     * @param generated GENERATED ALWAYS AS (…) STORED 의 식, 없으면 null
     * @param check     CHECK 조건(컬럼 이름 포함 완성식), 없으면 null
     * @param value     값 변환 규칙(3단계 적재기·4단계 반영기·검증이 같은 규칙을 쓴다)
     * @param notes     보고서 비고
     */
    public record ColumnPlan(
            SourceCatalog.Column source,
            String srcName,
            String srcType,
            String tgtName,
            String tgtType,
            String collate,
            boolean nullable,
            String identity,
            String defaultExpr,
            String generated,
            String check,
            ValueRule value,
            List<String> notes) {
    }

    /**
     * 값 변환 규칙. 해당 없는 항목은 null.
     *
     * @param trailingSpace keep | rtrim (문자)
     * @param caseRule      keep | upper | lower (문자)
     * @param nulChar       fail | strip | replace (문자)
     * @param sentinel      keep | null | infinity (날짜)
     * @param round         half_up | truncate (원천 소수 자릿수를 줄일 때)
     */
    public record ValueRule(String trailingSpace, String caseRule, String nulChar, String sentinel, String round) {
    }

    /** PK·UNIQUE 제약. columns 는 대상 컬럼 이름 */
    public record KeyPlan(String name, List<String> columns) {
    }

    /**
     * 적재 뒤 만들 UNIQUE 제약·인덱스.
     *
     * @param srcName  원천 이름
     * @param ddl      CREATE INDEX / ALTER TABLE … ADD CONSTRAINT 문(세미콜론 없음)
     * @param note     보고서 비고(규칙 결정), 없으면 null
     */
    public record IndexPlan(String srcName, String name, String ddl, String note) {
    }

    public record ForeignKeyPlan(String srcName, String name, String ddl) {
    }

    /**
     * @param ddl CREATE SEQUENCE 문(세미콜론 없음)
     */
    public record SequencePlan(
            SourceCatalog.Sequence source,
            String tgtSchema,
            String tgtName,
            String tgtType,
            String ddl,
            List<Issue> issues) {
    }
}
